version: '3'
services:
  todo_app:
    build: .
    ports:
      - 2345:3000
    working_dir: /app
    environment:
      MYSQL_HOST: mysql-todo-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: todo_database
    networks:
      - todo_network_example:

  mysql-todo-app:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_database
    networks:
      todo_network_example:
        aliases: 
        - mysql

volumes:
  mysql:

networks:
  todo_network_example: